### ISSUE TITLE
Please remove me from this list.

### ISSUE THREAD

**Issue by welcoMattic** [zeke/electron-developers#1]
It's not because I forked 1 day an Electron dependent repository that I'm an "Electron developer".
Please get smart growth hacker, before generate stupid list and get us spammed.

**Comment by zeke** [comment]
Du calme, Mathieu. Not a growth hacker.

**Comment by welcoMattic** [comment]
Be realistic, most of dev on the list has only one "Electron repo", is it smart? I don't think so.
